config/routes.rb
RetroRails::Application.routes.draw do

  root :to => "home#index"

  resources :retrospectives
  resources :users do
    resources :retrospectives
  end

  resources :retrospectives do
    resources :goods
    resources :bads
  end


  post   "/votes/:model/:id" => "votes#create", as: :vote_up
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down

  get "/retrospectives/:retrospective_id/bads/:id/keep" => "bads#keep", as: :retrospective_bad_keeps
  get "/retrospectives/:retrospective_id/bads/:id/good" => "bads#to_good", as: :retrospective_bad_to_good

  match "/signup"          => "users#new"
  match "/signin"          => "users#authenticate"
  match "/logout"          => "users#logout"
  match "/password"        => "users#password"
  match "/password_update" => "users#password_update"

  # Error 404 Handler
  match "*path" => "application#not_found"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :logged_at, :name, :password, :password_confirmation

  has_many :retrospectives

  before_create :encrypt_password

  validates :email,    :presence =>true, :uniqueness=>true
  validates :name,     :presence =>true
  validates :password, :presence =>true, :length => { :minimum => 5, :maximum => 40 }, :confirmation => true
  validates_confirmation_of :password

  def self.md5(text)
    Digest::MD5.hexdigest(text)
  end

  def encrypt_password
    if password.present?
      self.password = Digest::MD5.hexdigest(self.password)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password == md5(password)
      user
    end
  end

end

app/controllers/users_controller.rb
# encoding : utf-8
class UsersController < ApplicationController

  before_filter :ensure_authentication, :only => [:edit, :update, :destroy, :index, :password, :password_update]


  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    render layout: false
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # GET /password
  def password
    @user = current_user
  end

  def password_update
    @user = current_user
    @user.password = User.md5(params[:user][:password])
    @user.password_confirmation = User.md5(params[:user][:password_confirmation])

    respond_to do |format|
      if !params[:user][:password].blank? and @user.save
        session[:user] = @user
        format.html { redirect_to "/retrospectives", notice: 'Sua senha foi alterada!' }
      else
        format.html { render action: "password", notice: 'Suas senhas não conferem!' }
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, alert: 'Sua conta foi criada!' }
      else
        format.html { render action: "new", layout: false }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]

    respond_to do |format|
      if @user.save
        format.html { redirect_to "/retrospectives", notice: 'Seu dados foram atualizados!' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def authenticate
    user = User.authenticate(params[:email], params[:password])

    if user
      session[:user] = user
      redirect_to "/retrospectives", notice: "Olá #{user.name}, bem vindo ao Retrospectiba!"
    else
      redirect_to root_url, notice: 'Usuário ou senha inválida'
    end
  end

  def logout
    user = User.find(current_user.id)
    user.save
    session[:user] = nil
    redirect_to root_url, :alert => "Obrigado por ter usado o Retrospectiba!"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "nav-form"}) do |f| %>

  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Atenção!</h4>
      Os seguintes erros foram encontrados:
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder:"Nome", class: "span8" %> 
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder:"E-mail", class: "span8"  %> 
  </div>
  <div class="field">
    <%= f.password_field :password, placeholder:"Password", class: "span5"  %> 
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, placeholder:"Confirmação", class: "span5"  %> 
  </div>
  <div class="field">
    <% #= f.date_select :logged_at %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-primary btn-inverse" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><b>Perfil</b></li>
</ul>
<div class="row-fluid">
  <div class="span5">
    <img src="/assets/nelson.png"  title="<%= @current_user.name %>" alt="Ralph Steadman Artwork"/>
  </div><!-- div:span10 -->
  <div class="span6">
    <h3><%= @current_user.name %></h3>
    <legend></legend>
    <%= form_for(@user, html: {class: "nav-form"}) do |f| %>

      <% if @user.errors.any? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Atenção!</h4>
          Os seguintes erros foram encontrados:
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.text_field :name, placeholder:"Nome", class: "span8" %>
      </div>
      <div class="field">
        <%= f.text_field :email, placeholder:"E-mail", class: "span8"  %>
      </div>
      <div class="field">
        <% #= f.date_select :logged_at %>
      </div>
      <div class="actions">
        <%= f.submit "Salvar", class: "btn btn-primary btn-inverse" %>
      </div>
    <% end %>
  </div><!-- div:span3 -->
</div><!-- div:row -->

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fosformol</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-40782711-1', 'retrospectiba.com');
      ga('send', 'pageview');
    </script>
  </head>
  <body id="home">
    <div class="container">
      <div class="hero-unit">
        <div class="page-header">
          <div class="row-fluid">
            <ul class="breadcrumb">
              <li><%= link_to 'Retrospectiba', root_path, class: "btn btn-link" %><span class="divider">/</span></li>
              <li><b>Novo Usuário</b></li>
            </ul>
            <div class="span5">
              <img src="/assets/homer-smart.png"/>
            </div><!-- /div:span5 -->
            <div class="span6">
              <h3>Cadastre-se.</h3>
              <legend></legend>
              <%= render 'form' %>
              <div class="controls">
                <span class="help-block">Você <span class="label label-important">não</span> receberá um e-mail para ativar sua conta.</span>
              </div><!-- div.controls -->
            </div><!-- /div:span2 -->
          </div><!-- div:page-header -->
        </div><!-- div.row-fluid -->
      </div><!--/div:hero-unit-->
    </div><!-- /div:container-->
    <footer>
      <div class="container">
        <p>
          <span class="label label-info">www.retrospectiba.com</span>
          <span class="label label-important"><a href="https://github.com/zekitow/retro/network/members" target="_blank">contribuidores</a></span>
        </p>
      </div><!-- /div:container-->
    </footer>
  </body>
</html>

app/views/users/password.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><b>Alterar Senha</b></li>
</ul>
<div class="row-fluid">
  <div class="span6">
    <img src="/assets/willy.png"  title="<%= @current_user.name %>" alt="Ralph Steadman Artwork"/>
  </div><!-- div:span10 -->
  <div class="span5">
    <h3><%= @current_user.name %></h3>
    <legend></legend>
    <p>Não esqueça de anotar sua nova senha.</p>
    <%= form_for(@user, :url => password_update_path, html: {class: "nav-form"}) do |f| %>
      <% if @user.errors.any? or notice %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Atenção!</h4>
          Os seguintes erros foram encontrados:
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.password_field :password, placeholder:"Password", class: "span5"  %>
      </div>
      <div class="field">
        <%= f.password_field :password_confirmation, placeholder:"Confirmação", class: "span5"  %>
      </div>
      <div class="actions">
        <%= f.submit "Salvar", class: "btn btn-primary btn-inverse" %>
        <% unless @current_user %>
        <%= link_to 'Voltar', root_path, class: "btn btn-link" %>
        <% end %>
      </div>
    <% end %>
  </div><!-- div:span3 -->
</div><!-- div:row -->

app/views/users/signup.html.erb
<h1>Cadastre-se</h1>

<%= render 'form' %>