config/routes.rb
RetroRails::Application.routes.draw do

  root :to => "home#index"

  resources :retrospectives
  resources :users do
    resources :retrospectives
  end

  resources :retrospectives do
    resources :goods
    resources :bads
  end


  post   "/votes/:model/:id" => "votes#create", as: :vote_up
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down

  get "/retrospectives/:retrospective_id/bads/:id/keep" => "bads#keep", as: :retrospective_bad_keeps
  get "/retrospectives/:retrospective_id/bads/:id/good" => "bads#to_good", as: :retrospective_bad_to_good

  match "/signup"          => "users#new"
  match "/signin"          => "users#authenticate"
  match "/logout"          => "users#logout"
  match "/password"        => "users#password"
  match "/password_update" => "users#password_update"

  # Error 404 Handler
  match "*path" => "application#not_found"

end

app/models/retrospective.rb
class Retrospective < ActiveRecord::Base
  attr_accessible :name

  belongs_to :user

  has_many :goods
  has_many :bads

  validates :name, :user_id, :presence =>true
end

app/controllers/retrospectives_controller.rb
# encoding : utf-8
class RetrospectivesController < ApplicationController

  before_filter :ensure_authentication

  # GET /retrospectives
  # GET /retrospectives.json
  def index
    @user = current_user
    @retrospectives = Retrospective.where(:user_id => current_user.id)
    @retrospective = Retrospective.new
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def create
    @retrospective = Retrospective.new(params[:retrospective])
    @retrospective.user = @current_user

    if @retrospective.save
      notice = 'Sua nova retro foi criada!'
    else
      notice = 'LESSSS! Tente novamente.'
    end

    redirect_to '/retrospectives', notice: notice
  end

  # GET /retrospectives
  # GET /retrospectives.json
  def show
    @retrospective = Retrospective.find(params[:id])
    @worst = Retrospective.where("user_id = #{@current_user.id} and id < #{params[:id]}").order('created_at desc').first
    @good = Good.new
    @bad  = Bad.new
  end
end

app/views/retrospectives/_delete_bads.html.erb
<%= form_for([@retrospective, @bad], {remote: true, method: :delete, html: {name: "delete_bad", id: "delete_bad"}}) do |f| %>
    <div id="delete-bad" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Excluir Registro</h4>
      </div>
      <div class="modal-body">
        <p>Tem certeza que deseja apagar o registro?</p>
      </div>
      <div class="modal-footer">
        <%= f.submit "Excluir", class: "btn btn-primary", type: "submit" %>
      </div>
    </div>
<% end %>

app/views/retrospectives/_delete_goods.html.erb
<%= form_for([@retrospective, @good], {remote: true, method: :delete, html: {name: "delete_good", id: "delete_good"}}) do |f| %>
    <div id="delete-good" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Excluir Registro</h4>
      </div>
      <div class="modal-body">
        <p>Tem certeza que deseja apagar o registro?</p>
      </div>
      <div class="modal-footer">
        <%= f.submit "Excluir", class: "btn btn-primary", type: "submit" %>
      </div>
    </div>
<% end %>

app/views/retrospectives/_list_bads.html.erb
    <table class="table">
      <thead>
        <tr>
          <th>Descrição</th>
          <th>Ação</th>
          <th width="20"></th>
        </tr>
      </thead>
      <tbody>
        <% @retrospective.bads.each do |bad| %>
          <tr class="bad" id="bad-<%= bad.id %>">
            <td class="bad-desc"><%= bad.description %></td>
            <td class="bad-action"><%= bad.action %></td>
            <td id="<%= item_votes_id(bad) %>" class="votes"><%= bad.votes %></td>
            <td>
              <div class="btn-group">
                <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">Ações <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Gostei', vote_up_url(model: bad.class.to_s.downcase, id: bad.id), remote: true, method: :post %></li>
                  <li><%= link_to 'Não Gostei', vote_down_url(model: bad.class.to_s.downcase, id: bad.id), remote: true, method: :delete %></li>
                  <li>
                    <input type="hidden" value="<%= bad.id %>" />
                    <a href="#delete-bad" data-toggle="modal" class="btn-delete-bad">Excluir</a>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/retrospectives/_list_goods.html.erb
    <table class="table">
      <thead>
        <tr>
          <th>Descrição</th>
          <th width="20"></th>
        </tr>
      </thead>
      <tbody>
        <% @retrospective.goods.each do |good| %>
          <tr class="good" id="good-<%= good.id %>">
            <td class="good-desc"><%= good.description %></td>
            <td id="<%= item_votes_id(good) %>"class="votes"><%= good.votes %></td>
            <td>
              <div class="btn-group">
                <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">Ações <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Gostei', vote_up_url(model: good.class.to_s.downcase, id: good.id), remote: true, method: :post %></li>
                  <li><%= link_to 'Não Gostei', vote_down_url(model: good.class.to_s.downcase, id: good.id), remote: true, method: :delete %></li>
                  <li>
                    <input type="hidden" value="<%= good.id %>" />
                    <a href="#delete-good" data-toggle="modal" class="btn-delete-good">Excluir</a>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/retrospectives/_list_worst.html.erb
<% if @worst and @worst.bads.present? %>
  <div class="row-fluid">
    <div class="span12">
      <h4>Items da última retrospectiva:</h4>
      <table class="table">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Ação</th>
            <th width="100">Corrigido?</th>
          </tr>
        </thead>
        <tbody>
          <% @worst.bads.each do |bad| %>
            <tr class="warning">
              <td><%= bad.description %></td>
              <td><%= bad.action %></td>
              <td>
                <%= link_to 'Sim',  retrospective_bad_to_good_path(@retrospective, bad), class: 'btn btn-small btn-success' %>
                <%= link_to 'Não',  retrospective_bad_keeps_path(@retrospective, bad), class: 'btn btn-small btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!--/div:span5 -->
  </div><!-- div:row -->
<% end %>

app/views/retrospectives/_new_bad.html.erb
<%= form_for([@retrospective, @bad]) do |f| %>
  <%= f.hidden_field :retrospective_id, :value => @retrospective.id %>
  <div id="addRuim" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Ruim</h2>
    </div>
    <div class="modal-body">
        <% if @bad.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>Atenção!</h4>
            Os seguintes erros foram encontrados:
            <ul>
              <% @bad.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.text_field :description, placeholder:"Descrição", class: "span5" %>
        </div>
        <div class="field">
          <%= f.text_field :action, placeholder:"Ação", class: "span5" %>
        </div>
    </div>
    <div class="modal-footer">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/retrospectives/_new_good.html.erb
<%= form_for([@retrospective, @good]) do |f| %>
  <%= f.hidden_field :retrospective_id, :value => @retrospective.id %>
  <div id="addBom" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Bom</h2>
    </div>
    <div class="modal-body">
        <% if @good.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>Atenção!</h4>
            Os seguintes erros foram encontrados:
            <ul>
              <% @good.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.text_field :description, placeholder:"Descrição", class: "span5" %>
        </div>
    </div>
    <div class="modal-footer">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/retrospectives/_new_retro.html.erb
<%= form_for @retrospective  do |f| %>
    <div id="newRetro" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Nova Retrospectiva</h2>
    </div>
    <div class="modal-body">
        <% if @retrospective.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>Atenção!</h4>
            Os seguintes erros foram encontrados:
            <ul>
              <% @retrospective.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.text_field :name, class: "span5", value: "Sprint# #{@retrospectives.count + 1}" %>
        </div>
    </div>
    <div class="modal-footer">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/retrospectives/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><b>Retrospectivas</b></li>
</ul>
<div class="row-fluid">
  <div class="span6">
    <div class="page-header">
      <h3>Retrospectivas</h3>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Bom</th>
          <th>Ruim</th>
        </tr>
      </thead>
      <tbody>
        <% @retrospectives.each do |retro| %>
          <tr>
            <td><%= link_to "#{retro.name}", retrospective_path(retro)  %></td>
            <td><%= retro.try(:goods).try(:count) %></td>
            <td><%= retro.try(:bads).try(:count) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <a href="#newRetro" role="button" class="btn btn-inverse btn-large" data-toggle="modal">Nova Retrospectiva</a>
    <br />

  </div><!-- div:span6 -->
  <div class="span5">
    <img src="/assets/moe.png"  title="<%= @current_user.name %>" alt="Ralph Steadman Artwork"/>
  </div><!-- div:span6 -->
</div><!-- div:row -->

<%= render 'new_retro' %>

app/views/retrospectives/new.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, users_path %> <span class="divider">/</span></li>
  <li><%= link_to "Retrospectivas", user_retrospectives_path(@current_user) %> <span class="divider">/</span></li>
  <li><b>Nova</b></li>
</ul>

<div class="page-header">
  <h3>Nova Retrospectiva</h3>
</div>
<%= form_for(@retrospective, html: {class: "nav-form"}) do |f| %>

  <% if @retrospective.errors.any? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Atenção!</h4>
      Os seguintes erros foram encontrados:
      <ul>
      <% @retrospective.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="control-group">
      <label class="control-label" for="inputEmail">Email</label>
      <div class="controls">
        <input type="text" id="inputEmail" placeholder="Email">
      </div>
    </div>
    Sprint #: <%= f.text_field :sprint_number, placeholder:"Número", class: "span8" %>
  </div>
<% end %>

app/views/retrospectives/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><%= link_to 'Retrospectivas', retrospectives_path %> <span class="divider">/</span></li>
  <li><b><%= @retrospective.name %></b></li>
</ul>
<div class="alert alert-error hide" id="retrospectives-alert-error">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4></h4>
  <p></p>
</div>
<div class="alert alert-success hide" id="retrospectives-alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4></h4>
  <p></p>
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="page-header">
      <h3><%= @retrospective.name %></h3>
    </div>
  </div><!--/div:span5 -->
</div><!-- div:row -->
<%= render 'list_worst' %>
<div class="row-fluid">
  <div class="span6">
    <h4><a href="#addBom" role="button" class="btn btn-small btn-success" data-toggle="modal">Bom</a></h4>
    <%= render 'list_goods' %>
  </div><!-- div:span6 -->
  <div class="span6">
    <h4><a href="#addRuim" role="button" class="btn btn-small btn-danger" data-toggle="modal">Ruim</a></h4>
    <%= render 'list_bads' %>

  </div><!-- div:span6 -->
</div><!-- div:row -->

<%= render 'new_good' %>
<%= render 'new_bad' %>
<%= render 'delete_goods' %>
<%= render 'delete_bads' %>